/**
 * LLM client with three modes:
 *
 *   1. EIGEN_GATEWAY_URL set     → confidential routing through the Eigen AI gateway.
 *   2. ANTHROPIC_API_KEY set     → direct Anthropic SDK call.
 *   3. neither                   → returns a mock response.
 */
import Anthropic from '@anthropic-ai/sdk';
import type { HealthSummary } from './apple-health';
import type { Contributor } from './personas';

const SYSTEM_PROMPT = `You are a personal health agent for one user. You answer questions grounded ONLY in the JSON health data summary provided to you. You never invent data. If the summary doesn't contain what's needed to answer, say so plainly.

You are running inside a hardware-attested Trusted Execution Environment. Neither the operator of this service nor the model provider can read this conversation in plaintext outside the enclave.

Style: concise, direct, useful. Surface patterns. Do not give medical advice — this is decision support, not a doctor. If a question implies a medical decision (medication, diagnosis, surgery), say so and suggest consulting a clinician.`;

export interface LLMResult {
  text: string;
  via_gateway: boolean;
  model: string;
}

export async function chatWithLLM(
  userMessage: string,
  dataSummary: HealthSummary | null,
  cohortBlock: string,
): Promise<LLMResult> {
  const systemPrompt = SYSTEM_PROMPT + cohortBlock;
  const modelId = process.env.LLM_MODEL || 'anthropic/claude-sonnet-4-5';

  const grounded = dataSummary
    ? [
        `User question: ${userMessage}`,
        '',
        `User's health data summary (JSON, generated by the agent inside the TEE):`,
        '```json',
        JSON.stringify(dataSummary, null, 2),
        '```',
      ].join('\n')
    : `User question: ${userMessage}\n\n(No health data has been uploaded yet — say so and tell them how to upload.)`;

  // ----- Mode 1: Eigen AI gateway -----
  const gatewayUrl = process.env.EIGEN_GATEWAY_URL;
  if (gatewayUrl) {
    try {
      const text = await callGateway(gatewayUrl, systemPrompt, grounded);
      console.log('[llm] responded via gateway');
      return { text, via_gateway: true, model: modelId };
    } catch (err) {
      console.error('[llm] gateway error, falling back:', err);
    }
  }

  // ----- Mode 2: direct Anthropic SDK -----
  if (process.env.ANTHROPIC_API_KEY) {
    const bareModel = modelId.replace(/^anthropic\//, '');
    const text = await callAnthropicDirect(systemPrompt, grounded);
    console.log('[llm] responded via direct Anthropic SDK');
    return { text, via_gateway: false, model: bareModel };
  }

  // ----- Mode 3: mock -----
  console.log('[llm] responded via mock (no credentials)');
  return { text: buildMockResponse(userMessage, dataSummary, cohortBlock), via_gateway: false, model: 'mock' };
}

function buildMockResponse(
  userMessage: string,
  dataSummary: HealthSummary | null,
  cohortBlock: string,
): string {
  const lines = [
    '[mock LLM] No LLM credentials configured.',
    '',
    `You asked: "${userMessage}".`,
  ];
  if (dataSummary) {
    lines.push(
      `I can see ${Object.keys(dataSummary.metrics).length} metrics and ${dataSummary.workouts.count30d} workouts in your last 30 days.`,
    );
  } else {
    lines.push('No health data uploaded yet.');
  }
  if (cohortBlock) {
    lines.push('', 'Cohort context was injected (4 personas selected by similarity).');
  }
  lines.push(
    '',
    'Set EIGEN_GATEWAY_URL (production) or ANTHROPIC_API_KEY (local dev) to enable real responses.',
  );
  return lines.join('\n');
}

// ----------------------------------------------------------------------------

async function callGateway(
  baseUrl: string,
  systemPrompt: string,
  userContent: string,
): Promise<string> {
  const url = `${baseUrl.replace(/\/$/, '')}/v1/chat/completions`;
  const res = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      ...(process.env.EIGEN_GATEWAY_TOKEN
        ? { Authorization: `Bearer ${process.env.EIGEN_GATEWAY_TOKEN}` }
        : {}),
    },
    body: JSON.stringify({
      model: process.env.LLM_MODEL || 'anthropic/claude-sonnet-4-5',
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userContent },
      ],
      max_tokens: 800,
      temperature: 0.3,
    }),
  });
  if (!res.ok) {
    throw new Error(`gateway ${res.status}: ${await res.text().catch(() => '')}`);
  }
  const json = (await res.json()) as {
    choices?: { message?: { content?: string } }[];
  };
  return json.choices?.[0]?.message?.content || '(empty response from gateway)';
}

async function callAnthropicDirect(
  systemPrompt: string,
  userContent: string,
): Promise<string> {
  const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY! });
  const model = (process.env.LLM_MODEL || 'claude-sonnet-4-5').replace(/^anthropic\//, '');
  const resp = await client.messages.create({
    model,
    max_tokens: 800,
    temperature: 0.3,
    system: systemPrompt,
    messages: [{ role: 'user', content: userContent }],
  });
  const block = resp.content[0];
  if (block && block.type === 'text') return block.text;
  return '(empty response)';
}
